import type { WorkspaceStatisticsCopy } from './statistics.copy';

export const COPY_DE: WorkspaceStatisticsCopy = {
  subtitle: 'Überblick über Performance, Nachfrage und Wachstum',
  rangeGroupLabel: 'Zeitraum',
  range24h: '24h',
  range7d: '7 Tage',
  range30d: '30 Tage',
  range90d: '90 Tage',
  contextTitle: 'Analysekontext',
  contextSubtitle: 'Ein gemeinsamer Marktfilter steuert KPI, Chancen, Preise und Empfehlungen.',
  contextPeriodLabel: 'Zeitraum',
  contextCityLabel: 'Stadt',
  contextCategoryLabel: 'Kategorie',
  contextTrendLabel: 'Trend',
  contextAllCitiesLabel: 'Alle Städte',
  contextAllCategoriesLabel: 'Alle Kategorien',
  contextAllServicesLabel: 'Alle Services',
  contextResetLabel: 'Filter zurücksetzen',
  contextScopeGlobalLabel: 'Globaler Markt',
  contextScopeFocusLabel: 'Fokusmodus',
  contextHealthDemandLabel: 'Nachfrage',
  contextHealthCompetitionLabel: 'Wettbewerb',
  contextHealthActivityLabel: 'Aktivität',
  contextHealthDemandRising: 'Steigend',
  contextHealthDemandStable: 'Stabil',
  contextHealthDemandLimited: 'Begrenzt',
  contextHealthCompetitionHigh: 'Hoch',
  contextHealthCompetitionBalanced: 'Ausgeglichen',
  contextHealthCompetitionLow: 'Niedrig',
  contextHealthActivityHigh: 'Aktiv',
  contextHealthActivityStable: 'Stabil',
  contextHealthActivityLow: 'Ruhig',
  contextLowDataTitle: 'Zu wenig Daten für eine verlässliche Segmentanalyse',
  contextLowDataBody: 'Erweitern Sie den Zeitraum oder wechseln Sie zu Alle Städte bzw. Alle Kategorien.',
  backgroundErrorTitle: 'Aktualisierung fehlgeschlagen',
  backgroundErrorBody: 'Die sichtbaren Daten stammen noch aus dem vorherigen Analysekontext. Bitte versuchen Sie die Aktualisierung erneut.',
  exportLabel: 'Export CSV',
  modePlatform: 'Plattform',
  modePersonalized: 'Personalisiert',
  viewerModeLabel: 'Perspektive',
  viewerModeProviderLabel: 'Für Anbieter',
  viewerModeCustomerLabel: 'Für Auftraggeber',
  kpiTitle: 'KPI Übersicht',
  activityTitle: 'Aktivität der Plattform',
  activitySubtitle: 'Gesamtbestand von Anfragen und Angeboten im Zeitverlauf',
  marketHealthTitle: 'Market Health',
  marketHealthSubtitle: 'Operative Kennzahlen für Markt- und Wachstumsentscheidungen',
  decisionKiFallbackInsight:
    'Operative Kennzahlen zeigen den aktuellen Plattformzustand. Nutze schnelle Reaktionen und klare Positionierung, um Abschlusschancen zu verbessern.',
  activitySignalsUpdatedPrefix: 'Aktualisiert',
  activitySignalsBasedOnPrefix: 'Basierend auf Plattformaktivität der letzten',
  activityOfferRateLabel: 'Angebotsquote',
  activityResponseMedianLabel: 'Median Antwortzeit',
  activityUnansweredLabel: 'Unbeantwortet >24h',
  activityCancellationLabel: 'Stornoquote',
  activityCompletedLabel: 'Abschlüsse',
  activityAverageOrderValueLabel: 'Ø Auftragswert',
  activityGmvLabel: 'GMV',
  activityRevenueLabel: 'Plattform-Umsatz',
  activityNoResponse: 'Keine Antwortdaten',
  activityMinutesShortLabel: 'Min.',
  activityTakeRateSuffix: 'Take Rate',
  activityOfferRateHintPositive: 'Signal: Nachfrage wird solide in Angebote umgewandelt',
  activityOfferRateHintNegative: 'Risiko: Zu wenig Nachfrage wird in Angebote überführt',
  activityResponseFirstOfferHint: 'Zeit bis zum ersten Angebot',
  activityResponseActionHint: 'Aktion: erstes Angebot möglichst unter 2h senden',
  activityUnansweredRiskHint: 'Risiko: verlorene Aufträge ohne schnelle Reaktion',
  activityCancellationStableHint: 'Signal: stabile Abschlussqualität',
  activityCancellationUnstableHint: 'Risiko: instabile Abschlussqualität',
  activityCompletedSignalHint: 'Signal: bewiesene Lieferfähigkeit im aktuellen Markt',
  activityRevenueSignalTemplate: 'Signal: Monetarisierung funktioniert. {gmv} · {takeRate}% {suffix}',
  trendStableLabel: 'Trend stabil',
  trendNewTemplate: '+{value} neu {context}',
  trendSinceLastPeriodTemplate: '{delta} seit letzter Periode',
  trendContextTodayLabel: 'heute',
  trendContextWeekLabel: 'diese Woche',
  trendContextMonthLabel: 'diesen Monat',
  trendContext90DaysLabel: 'in 90 Tagen',
  reviewSingularLabel: 'Bewertung',
  reviewPluralLabel: 'Bewertungen',
  insightMetricRequestsLabel: 'Anfragen',
  insightMetricProvidersLabel: 'Anbieter',
  insightMetricRatioLabel: 'Verhältnis',
  insightMetricShareLabel: 'Anteil',
  insightMetricResponseTimeLabel: 'Antwortzeit',
  insightMetricSuccessRateLabel: 'Erfolgsquote',
  insightMetricProfileLabel: 'Profil',
  insightMetricProviderSearchesLabel: 'Anbieter-Suchen',
  insightMetricUnansweredLabel: 'Offen >24h',
  demandTitle: 'Nachfrage nach Kategorien',
  demandSubtitle: 'Wo aktuell die meisten Aufträge entstehen',
  demandExpandListLabel: 'Alle Kategorien anzeigen',
  citiesTitle: 'Städte & Regionen',
  citiesSubtitle: 'Marktaktivität nach Stadt im gewählten Zeitraum',
  citiesColumnRank: 'Rang',
  citiesColumnCity: 'Stadt',
  citiesColumnRequests: 'Anfragen',
  citiesColumnJobSearches: 'Auftrags-Suchen',
  citiesColumnProviderSearches: 'Anbieter-Suchen',
  citiesColumnMarketBalance: 'Market Balance',
  citiesFilterPlaceholder: 'Stadt suchen',
  citiesNoMatch: 'Keine Stadt gefunden.',
  citiesExpandListLabel: 'Alle Städte anzeigen',
  citiesCollapseListLabel: 'Liste reduzieren',
  citySignalHigh: 'Hohe Nachfrage',
  citySignalMedium: 'Ausgeglichen',
  citySignalLow: 'Viele Anbieter',
  citySignalNone: 'Kein Suchsignal',
  opportunityTitle: 'Opportunity Radar',
  opportunitySubtitle: 'Beste Marktchancen',
  opportunityEmpty: 'Noch keine Chancen-Daten verfügbar.',
  opportunityScoreLabel: 'Chance Score',
  opportunityDemandLabel: 'Nachfrage',
  opportunityProvidersLabel: 'Anbieter',
  opportunityBalanceLabel: 'Marktbalance',
  opportunityToneVeryHigh: 'Sehr hohe Nachfrage',
  opportunityToneHigh: 'Hohe Nachfrage',
  opportunityToneBalanced: 'Ausgeglichen',
  opportunityToneSupplyHeavy: 'Viele Anbieter',
  opportunityAxisDemand: 'Nachfrage',
  opportunityAxisCompetition: 'Konkurrenz',
  opportunityAxisGrowth: 'Marktwachstum',
  opportunityAxisActivity: 'Marktaktivität',
  opportunitySemanticVeryHigh: 'Sehr hoch',
  opportunitySemanticHigh: 'Hoch',
  opportunitySemanticNoticeable: 'Spürbar',
  opportunitySemanticMedium: 'Mittel',
  opportunitySemanticLow: 'Niedrig',
  opportunitySummaryVeryHigh:
    'Sehr hohe Nachfrage bei kontrollierbarem Wettbewerb. Jetzt ist ein starker Moment, um Sichtbarkeit in dieser Kategorie auszubauen.',
  opportunitySummaryGood:
    'Solide Nachfrage mit guter Marktaktivität. Mit klarer Positionierung kannst du hier zügig neue Aufträge gewinnen.',
  opportunitySummaryBalancedCompetitive:
    'Hohe Nachfrage trifft aktuell auf starken Wettbewerb. Gute Chancen haben Anbieter mit klarer Spezialisierung oder besserer Sichtbarkeit.',
  opportunitySummaryBalanced:
    'Die Marktchance ist ausgeglichen. Mit sauberem Profil und schnellen Reaktionen lässt sich diese Region effizient bedienen.',
  opportunitySummaryCompetitive:
    'Der Wettbewerb ist deutlich spürbar und drückt die Chance. Fokus auf Differenzierung und Preisstrategie verbessert die Abschlusswahrscheinlichkeit.',
  opportunitySummaryLowDemand:
    'Aktuell ist die Nachfrage in diesem Segment begrenzt. Prüfe Alternativen mit stärkerem Wachstum oder niedrigerem Wettbewerbsdruck.',
  opportunitySummaryLow:
    'Die Opportunity ist derzeit niedrig. Neue Chancen entstehen meist mit zusätzlicher Nachfrage oder besserer Marktaktivität.',
  opportunityStatusVeryHigh: 'Sehr hohe Chance',
  opportunityStatusGood: 'Gute Chance',
  opportunityStatusBalanced: 'Ausgeglichen',
  opportunityStatusCompetitive: 'Viele Anbieter',
  opportunityStatusLow: 'Niedrige Chance',
  opportunityWhyLabel: 'Warum gute Chance?',
  priceTitle: 'Preis-Intelligenz',
  priceSubtitle: 'Empfohlene Preisbereiche',
  priceRadarLabel: 'Marktpreis-Radar',
  pricePositionLabel: 'Empfohlener Preisbereich',
  priceOpportunityZoneLabel: 'Opportunity Zone',
  priceOpportunityHint: 'Empfohlener Bereich basiert auf aktuellen Abschlussraten.',
  pricePositionLowLabel: 'Niedrig',
  pricePositionHighLabel: 'Hoch',
  priceMarketAverageLabel: 'Marktdurchschnitt',
  priceRecommendedLabel: 'Empfohlener Bereich',
  priceRecommendationLabel: 'Empfehlung',
  priceSweetSpotLabel: 'Optimale Zone',
  priceProfitPotentialLabel: 'Profit Potential',
  priceProfitHighLabel: 'Sehr gute Marktchance',
  priceProfitMediumLabel: 'Solide Marktchance',
  priceProfitLowLabel: 'Vorsichtige Marktchance',
  priceRecommendationFallbackTemplate: 'Der Preisbereich {range} zeigt aktuell die höchste Abschlussrate{citySuffix}.',
  priceSignalLabel: 'Preis Signal',
  priceGuidanceNote: 'Orientierung für neue Angebote im gewählten Zeitraum.',
  priceNoData: 'Noch keine Preisdaten verfügbar.',
  profileTitle: 'Profil Performance',
  profileRevenueLabel: 'Umsatz',
  profileSubtitlePlatform: 'Von Anfragen bis zum erfolgreichen Abschluss und Umsatz',
  profileSubtitlePersonalized: 'Von Anfragen bis zum erfolgreichen Abschluss und Umsatz',
  profileComparisonHeadline: 'Deine Performance im Vergleich zum Markt',
  profileStrengthLabel: 'Stärke',
  profileMainLossLabel: 'Hauptverlust',
  profileRecommendationLineLabel: 'Empfehlung',
  profileSummaryFallback: 'Noch nicht genug Daten für eine verlässliche Einordnung.',
  comparisonUserLabel: 'Du',
  comparisonMarketLabel: 'Markt',
  comparisonGapLabel: 'Gap',
  clientActivityChartLabel: 'Du als Auftraggeber',
  providerActivityChartLabel: 'Du als Anbieter',
  insightsGeneratedLabel: 'Basierend auf aktuellen Plattformdaten',
  insightsAssistantAvatarLabel: 'KI',
  insightsAssistantName: "De'ci KI",
  insightsAssistantNote: 'Priorisiert Chancen, Risiken und nächste Schritte',
  insightsTypeChanceLabel: 'Chance',
  insightsTypeTrendLabel: 'Trend',
  insightsTypeRiskLabel: 'Risiko',
  insightsTypeActionLabel: 'Aktion',
  insightsTypeSignalLabel: 'Signal',
  insightsFeaturedLabel: 'Priorität',
  insightsFeaturedActionLabel: 'Mehr Details',
  decisionWhyLabel: 'Warum jetzt',
  decisionNextStepsLabel: 'Nächste Schritte',
  decisionStrategyTitle: 'Strategie-Empfehlung',
  decisionApplyStrategyLabel: 'Strategie anwenden',
  decisionOpenRequestsLabel: 'Passende Aufträge öffnen',
  decisionReasonMarketBalanceTemplate: 'Hohe Nachfrage bei relativ niedriger Anbieterzahl ({ratio}x Marktbalance).',
  decisionReasonDemandProvidersTemplate: '{demand} Nachfrage-Signale treffen auf nur {providers} aktive Anbieter.',
  decisionReasonGrowth: 'Das Segment zeigt zusätzlich klares Wachstum.',
  decisionReasonActivity: 'Die Marktaktivität ist hoch genug für schnelle Reaktionen und Abschlüsse.',
  decisionReasonDemand: 'Die Nachfrage ist im aktuellen Zeitraum überdurchschnittlich stark.',
  decisionReasonPriceCorridorTemplate: 'Der Preis-Korridor {range} wird aktuell durch Marktdaten gestützt.',
  decisionSummaryFallback: 'Nutze den aktuellen Kontext, um Fokus, Preis und Reaktionszeit sauber auszurichten.',
  decisionFocusStepTemplate: 'Fokus: {value}',
  decisionFocusFallback: 'Fokus: Globalen Markt beobachten und dann Opportunity wählen',
  decisionPriceStepTemplate: 'Preis: {value}',
  decisionPriceFallback: 'Preis: Erst nach belastbaren Marktpreisen skalieren',
  decisionResponseTimeStep: 'Reaktionszeit: unter 2h halten',
  personalizedDecisionSummaryFallback: 'Priorisiert Chancen, Risiken und nächste Schritte für dein aktuelles Markt-Setup.',
  userComparisonLabel: 'User vs Markt',
  userDecisionSubtitle: 'Vergleicht deine Performance mit dem aktuellen Markt',
  userGapTitle: 'Gap Analysis',
  userGapSummaryTemplate: 'Du verlierst {percent}% zwischen Angebot → Antwort. Das betrifft aktuell {count} Vorgänge.',
  userAtMarketLevelLabel: 'Auf Marktniveau',
  userPositionTitle: 'Performance vs Market',
  userPositionSubtitle: 'Deine Position im aktuellen Marktumfeld',
  userPositionTopPrefix: 'Top',
  userPositionTopSuffix: 'Anbieter',
  userPositionAverageLabel: 'Marktdurchschnitt',
  userPositionBelowLabel: 'Unterdurchschnittlich',
  userPositionSummaryTemplate: 'Du liegst aktuell auf dem {percentile}. Perzentil im Vergleich zum Markt.',
  userPositionSummaryFallback: 'Noch nicht genug Daten für eine belastbare Marktposition.',
  userPositionOverallLabel: 'Gesamt',
  userPositionCategoryLabel: 'Kategorie',
  userPositionCityLabel: 'Stadt',
  userRisksTitle: 'Risiken & Bottlenecks',
  userRisksSubtitle: 'Wo Performance verloren geht',
  userOpportunitiesTitle: 'Chancen für dich',
  userOpportunitiesSubtitle: 'Marktfelder mit besserem Fit für dein Profil',
  userActionsTitle: 'Nächste Schritte',
  userActionsSubtitle: 'Decision → Action',
  userActionsEmpty: 'Noch nicht genug Daten für konkrete nächste Schritte.',
  userRiskSeverityHigh: 'Hoch',
  userRiskSeverityMedium: 'Mittel',
  userRiskSeverityLow: 'Niedrig',
  userRiskSlowResponseTitle: 'Reaktionszeit zu hoch',
  userRiskSlowResponseBody: 'Du antwortest mit {user} Min. deutlich langsamer als der Markt mit {market} Min.',
  userRiskUnansweredTitle: 'Zu viele offene Anfragen',
  userRiskUnansweredBody: '{count} offene Vorgänge warten noch auf eine klare Reaktion.',
  userRiskVisibilityTitle: 'Niedrige Sichtbarkeit',
  userRiskVisibilityBody: 'Dein Profil ist erst zu {profile}% vollständig. Das drückt Sichtbarkeit und Vertrauen.',
  userOpportunityDemandTitle: 'Hohe Nachfrage in deinem Zielmarkt',
  userOpportunityDemandBody: '{city} · {category} zeigt aktuell starke Nachfrage für dein Setup.',
  userOpportunityCompetitionTitle: 'Wenig Anbieter im Segment',
  userOpportunityCompetitionBody: '{city} · {category} hat aktuell ein günstiges Nachfrage-Konkurrenz-Verhältnis.',
  userOpportunityCategoryTitle: 'Kategorie wächst',
  userOpportunityCategoryBody: '{category} entwickelt sich aktuell stärker als andere Segmente.',
  userPricingCurrentLabel: 'Dein Preis',
  userPricingProfileLabel: 'Dein Profil',
  userPricingRecommendedLabel: 'Empfohlen',
  userPricingAverageLabel: 'Markt',
  userPricingSummary: 'Pricing Strategy',
  userPricingStatusAbove: 'Zu hoch',
  userPricingStatusBelow: 'Zu niedrig',
  userPricingStatusWithin: 'Im Korridor',
  userPricingStatusUnknown: 'Noch offen',
  userPricingPositionLabel: 'Position',
  userPricingEffectLabel: 'Erwarteter Effekt',
  userPricingEffectAbove: 'Zu hoch → weniger Abschlüsse',
  userPricingEffectBelow: 'Zu niedrig → Marge bleibt liegen',
  userPricingEffectWithin: 'Im empfohlenen Bereich → gute Abschlusschance',
  userPricingEffectUnknown: 'Noch keine belastbare Preisposition verfügbar',
  userForYouLabel: 'Für dich',
  userFitLabel: 'Dein Fit',
  userFitHighLabel: 'hoch',
  userRecommendationLabel: 'Empfehlung',
  userRecommendationReliabilityHigh: 'Hohe Sicherheit',
  userRecommendationReliabilityMedium: 'Mittlere Sicherheit',
  userRecommendationReliabilityLow: 'Niedrige Sicherheit',
  userActionPriorityHigh: 'High',
  userActionPriorityMedium: 'Medium',
  userActionPriorityLow: 'Low',
  userActionImpactLabel: 'Impact',
  userActionEffectLabel: 'Erwarteter Effekt',
  userActionImpactHigh: 'Hoch',
  userActionImpactMedium: 'Mittel',
  userActionImpactLow: 'Niedrig',
  userActionRespondTitle: 'Antworte schneller',
  userActionRespondDetail: 'Ziel: erste Antwort unter {target} Minuten senden.',
  userActionRespondEffect: 'Mehr Antworten im Peak-Zeitfenster und weniger offene Vorgänge.',
  userActionPriceTitle: 'Preis anpassen',
  userActionPriceDetail: 'Positioniere neue Angebote näher bei {price}€.',
  userActionPriceEffect: 'Bessere Conversion im empfohlenen Preisfenster.',
  userActionFocusTitle: 'Marktfokus schärfen',
  userActionFocusDetail: 'Fokus auf {city} · {category} legen, solange Nachfrage und Balance stark sind.',
  userActionFocusEffect: 'Mehr Sichtbarkeit im stärksten Marktsegment.',
  userActionProfileTitle: 'Profil vervollständigen',
  userActionProfileDetail: 'Profil auf mindestens {target}% Vollständigkeit bringen.',
  userActionProfileEffect: 'Mehr Vertrauen und bessere Sichtbarkeit in passenden Aufträgen.',
  userActionFollowUpTitle: 'Offene Anfragen nachfassen',
  userActionFollowUpDetail: '{count} offene Vorgänge priorisiert beantworten oder schließen.',
  userActionFollowUpEffect: 'Weniger verlorene Vorgänge und klarere Pipeline.',
  growthTitle: 'Wachstum & Promotion',
  growthSubtitle: 'Mehr Sichtbarkeit und planbares Wachstum im aktuellen Markt',
  growthRecommendedPrefix: 'Empfohlen für',
  growthFeaturedBadge: 'Empfohlen',
  growthPriorityHigh: 'Priorität Hoch',
  growthHeroVisibilityTitle: 'Sichtbarkeit steigern',
  growthHeroVisibilityTitleWithContext: 'Sichtbarkeit in {context} steigern',
  growthExpectedEffectLabel: 'Erwarteter Effekt',
  growthPositionTitle: 'Deine Position',
  growthVisibilityLabel: 'Sichtbarkeit',
  growthVisibilityLow: 'Niedrig',
  growthResponseLabel: 'Antwortzeit',
  growthResponseMedium: 'Mittel',
  growthWhyNowTitle: 'Warum jetzt?',
  growthDemandInContext: 'Hohe Nachfrage in {context}',
  growthDemandGeneric: 'Hohe Nachfrage im aktuellen Markt',
  growthMarketChanceCurrent: 'Gute Marktchance im aktuellen Zeitraum',
  growthVisibilityBelowAverage: 'Dein Profil liegt unter dem lokalen Durchschnitt',
  growthFocusLabel: 'Fokus',
  growthDemandLabel: 'Nachfrage',
  growthDemandHighValue: 'Hoch',
  growthCompetitionLabel: 'Wettbewerb',
  growthCompetitionMedium: 'Mittel',
  growthConversionLabel: 'Conversion',
  growthConversionOptimizable: 'Optimierbar',
  growthMarketCompareLabel: 'Marktvergleich',
  growthMarketCompareAvailable: 'Verfügbar',
  growthHighlightCta: 'Sichtbarkeit erhöhen',
  growthLocalAdsCta: 'Region ansehen',
  growthPremiumCta: 'Insights öffnen',
  growthNextStepsTitle: 'Nächste Schritte',
  growthNextStepVisibility: 'Profil sichtbarer machen',
  growthNextStepLocalAds: 'Werbung aktivieren',
  growthNextStepLocalAdsWithContext: 'Werbung in {context} aktivieren',
  growthNextStepPricing: 'Preisstrategie prüfen',
  kpiSuccessRateLabel: 'Erfolgsquote',
  kpiNoCompletedJobs: 'Noch keine Abschlüsse',
  kpiActiveProvidersLabel: 'Aktive Anbieter',
  kpiActiveRequestsHintSuffix: 'aktive Aufträge',
  kpiActiveCitiesLabel: 'Aktive Städte',
  kpiWithDemandHint: 'mit Nachfrage',
  kpiAverageRatingLabel: 'Durchschnittsbewertung',
  kpiNoOpenRequests: 'Keine offenen Anfragen',
  kpiTotalInRangeHintSuffix: 'insgesamt im Zeitraum',
  kpiLast7DaysHintSuffix: 'in den letzten 7 Tagen',
  kpiNoRecentOffers7d: 'Noch keine Angebote in den letzten 7 Tagen',
  kpiResponseTimeLabel: 'Antwortzeit',
  kpiNoResponseTimeData: 'Noch keine Antwortzeit-Daten',
  kpiFastResponseHint: 'Stark: unter 30 Min.',
  kpiResponseTargetHint: 'Ziel: unter 30 Min.',
  kpiAcceptedOffersHintSuffix: 'akzeptierte Angebote',
  kpiNoSentOffers: 'Noch keine gesendeten Angebote',
  kpiProfileCompletenessLabel: 'Profil Vollständigkeit',
  kpiStrongProfileHint: 'Starkes Profil',
  kpiImproveProfileHint: 'Profil ausbauen für mehr Sichtbarkeit',
  emptyDemand: 'Noch keine Kategoriedaten für diesen Zeitraum.',
  emptyCities: 'Noch keine Städtedaten verfügbar.',
  emptyInsights: 'Noch keine Insights verfügbar.',
  emptyActivity: 'Noch keine Aktivitätsdaten.',
  fallbackGeneralCategoryLabel: 'Generalistisch',
  peakLabel: 'Höchster Aktivitätspunkt',
  bestWindowLabel: 'Bestes Zeitfenster',
  updatedLabel: 'Letzte Aktualisierung',
  requestsLabel: 'Anfragen',
  offersLabel: 'Angebote',
  reviewsLabel: 'Bewertungen',
  stage1LabelPlatform: 'Anfragen',
  stage2LabelPlatform: 'Angebote',
  stage3LabelPlatform: 'Abschlüsse',
  stage4LabelPlatform: 'Abgeschlossene Aufträge',
  stage1LabelPersonalized: 'Offene Anfragen',
  stage2LabelPersonalized: 'Gesendete Angebote',
  stage3LabelPersonalized: 'Akzeptierte Angebote',
  stage4LabelPersonalized: 'Abgeschlossene Aufträge',
  funnelRequestsLabel: 'Anfragen',
  funnelRequestsCompactLabel: 'Anfragen',
  funnelOffersLabel: 'Angebote von Anbietern',
  funnelOffersCompactLabel: 'Angebote',
  funnelConfirmedLabel: 'Bestätigte Rückmeldungen',
  funnelConfirmedCompactLabel: 'Rückmeldungen',
  funnelClosedLabel: 'Geschlossene Verträge',
  funnelClosedCompactLabel: 'Verträge',
  funnelCompletedLabel: 'Erfolgreich abgeschlossen',
  funnelCompletedCompactLabel: 'Abgeschlossen',
  funnelProfitLabel: 'Gewinnsumme',
  funnelProfitCompactLabel: 'Gewinn',
  funnelRateOfferLabel: 'Antwortquote',
  funnelRateConfirmationLabel: 'Zustimmungsrate',
  funnelRateClosureLabel: 'Abschlussrate',
  funnelRateCompletionLabel: 'Erfüllungsquote',
  funnelRateAvgRevenueLabel: 'Ø Umsatz / Auftrag',
  funnelSummaryPrefix: 'Von',
  funnelSummaryMiddle: 'Anfragen wurden',
  funnelSummarySuffix: 'erfolgreich abgeschlossen.',
  funnelDropoffLabel: 'Drop-off Highlight',
  funnelEmptyTitle: 'Noch keine Funnel-Daten verfügbar',
  funnelEmptyBody:
    'Sobald erste Anfragen, Angebote und Abschlüsse vorliegen, erscheint hier deine Performance über die Plattform.',
  funnelError: 'Die Funnel-Daten konnten nicht geladen werden. Bitte versuche es später erneut.',
  conversionLabel: 'Conversion',
  growthCta: 'Mehr entdecken',
};
