import type { WorkspaceStatisticsCopy } from './statistics.copy';

export const COPY_EN: WorkspaceStatisticsCopy = {
  subtitle: 'Overview of performance, demand, and growth',
  rangeGroupLabel: 'Time range',
  range24h: '24h',
  range7d: '7 days',
  range30d: '30 days',
  range90d: '90 days',
  contextTitle: 'Analysis context',
  contextSubtitle: 'One shared market filter drives KPI, opportunities, pricing, and recommendations.',
  contextPeriodLabel: 'Period',
  contextCityLabel: 'City',
  contextCategoryLabel: 'Category',
  contextTrendLabel: 'Trend',
  contextAllCitiesLabel: 'All cities',
  contextAllCategoriesLabel: 'All categories',
  contextAllServicesLabel: 'All services',
  contextResetLabel: 'Reset filters',
  contextScopeGlobalLabel: 'Global market',
  contextScopeFocusLabel: 'Focus mode',
  contextHealthDemandLabel: 'Demand',
  contextHealthCompetitionLabel: 'Competition',
  contextHealthActivityLabel: 'Activity',
  contextHealthDemandRising: 'Rising',
  contextHealthDemandStable: 'Stable',
  contextHealthDemandLimited: 'Limited',
  contextHealthCompetitionHigh: 'High',
  contextHealthCompetitionBalanced: 'Balanced',
  contextHealthCompetitionLow: 'Low',
  contextHealthActivityHigh: 'Active',
  contextHealthActivityStable: 'Stable',
  contextHealthActivityLow: 'Quiet',
  contextLowDataTitle: 'Not enough data for reliable segment analysis',
  contextLowDataBody: 'Expand the period or switch to all cities or all categories.',
  backgroundErrorTitle: 'Update failed',
  backgroundErrorBody: 'The visible data still comes from the previous analysis context. Please try the refresh again.',
  exportLabel: 'Export CSV',
  modePlatform: 'Platform',
  modePersonalized: 'Personalized',
  viewerModeLabel: 'Perspective',
  viewerModeProviderLabel: 'For providers',
  viewerModeCustomerLabel: 'For customers',
  kpiTitle: 'KPI overview',
  activityTitle: 'Platform activity',
  activitySubtitle: 'New requests and offers over time',
  marketHealthTitle: 'Market Health',
  marketHealthSubtitle: 'Operational metrics for market and growth decisions',
  decisionKiFallbackInsight:
    'Operational metrics reflect current platform health. Faster responses and clearer positioning can improve close rates.',
  activitySignalsUpdatedPrefix: 'Updated',
  activitySignalsBasedOnPrefix: 'Based on platform activity over the last',
  activityOfferRateLabel: 'Offer rate',
  activityResponseMedianLabel: 'Median response time',
  activityUnansweredLabel: 'Unanswered >24h',
  activityCancellationLabel: 'Cancellation rate',
  activityCompletedLabel: 'Completed jobs',
  activityAverageOrderValueLabel: 'Avg order value',
  activityGmvLabel: 'GMV',
  activityRevenueLabel: 'Platform revenue',
  activityNoResponse: 'No response data',
  activityMinutesShortLabel: 'min',
  activityTakeRateSuffix: 'Take rate',
  activityOfferRateHintPositive: 'Signal: demand is converting into offers',
  activityOfferRateHintNegative: 'Risk: too little demand is converting into offers',
  activityResponseFirstOfferHint: 'Time to first offer',
  activityResponseActionHint: 'Action: keep the first offer below 2h',
  activityUnansweredRiskHint: 'Risk: lost jobs without a fast response',
  activityCancellationStableHint: 'Signal: stable close quality',
  activityCancellationUnstableHint: 'Risk: unstable close quality',
  activityCompletedSignalHint: 'Signal: proven delivery capacity in the current market',
  activityRevenueSignalTemplate: 'Signal: monetization is working. {gmv} · {takeRate}% {suffix}',
  trendStableLabel: 'Trend stable',
  trendNewTemplate: '+{value} new {context}',
  trendSinceLastPeriodTemplate: '{delta} since last period',
  trendContextTodayLabel: 'today',
  trendContextWeekLabel: 'this week',
  trendContextMonthLabel: 'this month',
  trendContext90DaysLabel: 'in 90 days',
  reviewSingularLabel: 'review',
  reviewPluralLabel: 'reviews',
  insightMetricRequestsLabel: 'Requests',
  insightMetricProvidersLabel: 'Providers',
  insightMetricRatioLabel: 'Ratio',
  insightMetricShareLabel: 'Share',
  insightMetricResponseTimeLabel: 'Response time',
  insightMetricSuccessRateLabel: 'Success rate',
  insightMetricProfileLabel: 'Profile',
  insightMetricProviderSearchesLabel: 'Provider searches',
  insightMetricUnansweredLabel: 'Open >24h',
  demandTitle: 'Demand by category',
  demandSubtitle: 'Where market demand is currently highest',
  demandExpandListLabel: 'Show all categories',
  citiesTitle: 'Cities & regions',
  citiesSubtitle: 'Market activity by city in selected range',
  citiesColumnRank: 'Rank',
  citiesColumnCity: 'City',
  citiesColumnRequests: 'Requests',
  citiesColumnJobSearches: 'Job searches',
  citiesColumnProviderSearches: 'Provider searches',
  citiesColumnMarketBalance: 'Market balance',
  citiesFilterPlaceholder: 'Search city',
  citiesNoMatch: 'No matching city found.',
  citiesExpandListLabel: 'Show all cities',
  citiesCollapseListLabel: 'Show fewer',
  citySignalHigh: 'High demand',
  citySignalMedium: 'Balanced',
  citySignalLow: 'High provider activity',
  citySignalNone: 'No search signal',
  opportunityTitle: 'Opportunity radar',
  opportunitySubtitle: 'Best market opportunities',
  opportunityEmpty: 'No opportunity data available yet.',
  opportunityScoreLabel: 'Chance score',
  opportunityDemandLabel: 'Demand',
  opportunityProvidersLabel: 'Providers',
  opportunityBalanceLabel: 'Market balance',
  opportunityToneVeryHigh: 'Very high demand',
  opportunityToneHigh: 'High demand',
  opportunityToneBalanced: 'Balanced',
  opportunityToneSupplyHeavy: 'High provider activity',
  opportunityAxisDemand: 'Demand',
  opportunityAxisCompetition: 'Competition',
  opportunityAxisGrowth: 'Market growth',
  opportunityAxisActivity: 'Market activity',
  opportunitySemanticVeryHigh: 'Very high',
  opportunitySemanticHigh: 'High',
  opportunitySemanticNoticeable: 'Noticeable',
  opportunitySemanticMedium: 'Medium',
  opportunitySemanticLow: 'Low',
  opportunitySummaryVeryHigh:
    'Demand is very high while competition stays manageable. This is a strong moment to increase visibility in this category.',
  opportunitySummaryGood:
    'Stable demand and healthy market activity create good momentum. A clear positioning can help you win new jobs quickly.',
  opportunitySummaryBalancedCompetitive:
    'Strong demand currently meets strong competition. Best chances come from sharper specialization and stronger visibility.',
  opportunitySummaryBalanced:
    'The market is balanced right now. A strong profile and fast response times can unlock consistent opportunities.',
  opportunitySummaryCompetitive:
    'Competition pressure is high and limits upside. Better differentiation and pricing strategy can improve conversion.',
  opportunitySummaryLowDemand:
    'Demand in this segment is currently limited. Consider alternatives with stronger growth or lower competitive pressure.',
  opportunitySummaryLow:
    'Opportunity is currently low. Better demand or higher market activity is needed before scaling efforts here.',
  opportunityStatusVeryHigh: 'Very high opportunity',
  opportunityStatusGood: 'Good opportunity',
  opportunityStatusBalanced: 'Balanced',
  opportunityStatusCompetitive: 'Competitive',
  opportunityStatusLow: 'Low opportunity',
  opportunityWhyLabel: 'Why this is a good opportunity',
  priceTitle: 'Market price radar',
  priceSubtitle: 'Recommended range based on current close rates.',
  priceRadarLabel: 'Market price radar',
  pricePositionLowLabel: 'Low',
  pricePositionHighLabel: 'High',
  priceMarketAverageLabel: 'Market average',
  priceRecommendationLabel: 'Recommendation',
  priceProfitPotentialLabel: 'Profit potential',
  priceProfitHighLabel: 'Strong market potential',
  priceProfitMediumLabel: 'Solid market potential',
  priceProfitLowLabel: 'Cautious market potential',
  priceRecommendationFallbackTemplate: 'The range {range} currently shows the highest close rate{citySuffix}.',
  priceNoData: 'No pricing data available yet.',
  profileTitle: 'Profile performance',
  profileRevenueLabel: 'Revenue',
  profileSubtitlePlatform: 'From requests to successful completion and revenue',
  profileSubtitlePersonalized: 'From requests to successful completion and revenue',
  profileComparisonHeadline: 'Your performance compared with the market',
  profileStrengthLabel: 'Strength',
  profileMainLossLabel: 'Main loss',
  profileRecommendationLineLabel: 'Recommendation',
  profileSummaryFallback: 'Not enough data yet for a reliable assessment.',
  comparisonUserLabel: 'You',
  comparisonMarketLabel: 'Market',
  comparisonGapLabel: 'Gap',
  clientActivityChartLabel: 'You as client',
  providerActivityChartLabel: 'You as provider',
  insightsGeneratedLabel: 'Based on current platform data',
  insightsAssistantAvatarLabel: 'AI',
  insightsAssistantName: "De'ci AI",
  insightsAssistantNote: 'Prioritizing opportunities, risks, and next steps',
  insightsTypeChanceLabel: 'Chance',
  insightsTypeTrendLabel: 'Trend',
  insightsTypeRiskLabel: 'Risk',
  insightsTypeActionLabel: 'Action',
  insightsTypeSignalLabel: 'Signal',
  insightsFeaturedLabel: 'Priority',
  insightsFeaturedActionLabel: 'View details',
  decisionWhyLabel: 'Why now',
  decisionNextStepsLabel: 'Next steps',
  decisionStrategyTitle: 'Strategy recommendation',
  decisionApplyStrategyLabel: 'Apply strategy',
  decisionOpenRequestsLabel: 'Open matching requests',
  decisionReasonMarketBalanceTemplate: 'Strong demand with relatively low provider pressure ({ratio}x market balance).',
  decisionReasonDemandProvidersTemplate: '{demand} demand signals currently meet only {providers} active providers.',
  decisionReasonGrowth: 'The segment also shows clear growth.',
  decisionReasonActivity: 'Market activity is high enough to support fast response and conversion.',
  decisionReasonDemand: 'Demand is above average in the current time range.',
  decisionReasonPriceCorridorTemplate: 'The {range} pricing corridor is currently supported by market data.',
  decisionSummaryFallback: 'Use the current context to align focus, pricing, and response speed.',
  decisionFocusStepTemplate: 'Focus: {value}',
  decisionFocusFallback: 'Focus: review the global market, then choose an opportunity',
  decisionPriceStepTemplate: 'Price: {value}',
  decisionPriceFallback: 'Price: scale only after reliable pricing signals',
  decisionResponseTimeStep: 'Response time: keep it under 2h',
  personalizedDecisionSummaryFallback: 'Prioritizes opportunities, risks, and next steps for your current market setup.',
  userComparisonLabel: 'User vs Market',
  userDecisionSubtitle: 'Compares your performance with the current market',
  userGapTitle: 'Gap analysis',
  userGapSummaryTemplate: 'You lose {percent}% between offer → response. That currently affects {count} cases.',
  userAtMarketLevelLabel: 'At market level',
  userPositionTitle: 'Performance vs market',
  userPositionSubtitle: 'Your current market position',
  userPositionTopPrefix: 'Top',
  userPositionTopSuffix: 'providers',
  userPositionAverageLabel: 'Market average',
  userPositionBelowLabel: 'Below average',
  userPositionSummaryTemplate: 'You currently rank around the {percentile}th percentile versus the market.',
  userPositionSummaryFallback: 'Not enough data for a reliable market position yet.',
  userPositionOverallLabel: 'Overall',
  userPositionCategoryLabel: 'Category',
  userPositionCityLabel: 'City',
  userRisksTitle: 'Risks & bottlenecks',
  userRisksSubtitle: 'Where performance is leaking',
  userOpportunitiesTitle: 'Opportunities for you',
  userOpportunitiesSubtitle: 'Markets with a stronger fit for your profile',
  userActionsTitle: 'Next steps',
  userActionsSubtitle: 'Decision → Action',
  userActionsEmpty: 'Not enough data yet for concrete next steps.',
  userRiskSeverityHigh: 'High',
  userRiskSeverityMedium: 'Medium',
  userRiskSeverityLow: 'Low',
  userRiskSlowResponseTitle: 'Response time is too slow',
  userRiskSlowResponseBody: 'You reply in {user} min, slower than the market at {market} min.',
  userRiskUnansweredTitle: 'Too many open requests',
  userRiskUnansweredBody: '{count} open cases still need a clear reply.',
  userRiskVisibilityTitle: 'Low visibility',
  userRiskVisibilityBody: 'Your profile is only {profile}% complete. That reduces visibility and trust.',
  userOpportunityDemandTitle: 'High demand in your target market',
  userOpportunityDemandBody: '{city} · {category} currently shows strong demand for your setup.',
  userOpportunityCompetitionTitle: 'Low competition in segment',
  userOpportunityCompetitionBody: '{city} · {category} currently has favorable demand-to-competition balance.',
  userOpportunityCategoryTitle: 'Category is growing',
  userOpportunityCategoryBody: '{category} is currently outgrowing other segments.',
  userPricingCurrentLabel: 'Your price',
  userPricingProfileLabel: 'Your profile',
  userPricingRecommendedLabel: 'Recommended',
  userPricingAverageLabel: 'Market',
  userPricingSummary: 'Pricing strategy',
  userPricingStatusAbove: 'Too high',
  userPricingStatusBelow: 'Too low',
  userPricingStatusWithin: 'In range',
  userPricingStatusUnknown: 'Open',
  userPricingPositionLabel: 'Position',
  userPricingEffectLabel: 'Expected effect',
  userPricingEffectAbove: 'Too high → fewer conversions',
  userPricingEffectBelow: 'Too low → margin left on the table',
  userPricingEffectWithin: 'In corridor → strong close potential',
  userPricingEffectUnknown: 'No reliable pricing position yet',
  userForYouLabel: 'For you',
  userFitLabel: 'Your fit',
  userFitHighLabel: 'high',
  userRecommendationLabel: 'Recommendation',
  userRecommendationReliabilityHigh: 'High confidence',
  userRecommendationReliabilityMedium: 'Medium confidence',
  userRecommendationReliabilityLow: 'Low confidence',
  userActionPriorityHigh: 'High',
  userActionPriorityMedium: 'Medium',
  userActionPriorityLow: 'Low',
  userActionImpactLabel: 'Impact',
  userActionEffectLabel: 'Expected effect',
  userActionImpactHigh: 'High',
  userActionImpactMedium: 'Medium',
  userActionImpactLow: 'Low',
  userActionRespondTitle: 'Reply faster',
  userActionRespondDetail: 'Target: send the first reply within {target} minutes.',
  userActionRespondEffect: 'More replies during peak demand windows and fewer open items.',
  userActionPriceTitle: 'Adjust price',
  userActionPriceDetail: 'Move new offers closer to {price}€.',
  userActionPriceEffect: 'Better conversion inside the recommended pricing corridor.',
  userActionFocusTitle: 'Sharpen market focus',
  userActionFocusDetail: 'Focus on {city} · {category} while demand and balance stay strong.',
  userActionFocusEffect: 'More visibility in the strongest market segment.',
  userActionProfileTitle: 'Complete profile',
  userActionProfileDetail: 'Bring the profile to at least {target}% completeness.',
  userActionProfileEffect: 'More trust and stronger visibility in matching jobs.',
  userActionFollowUpTitle: 'Follow up on open requests',
  userActionFollowUpDetail: 'Prioritize {count} open cases for reply or closure.',
  userActionFollowUpEffect: 'Fewer lost pipeline items and a clearer workflow.',
  growthTitle: 'Growth & promotion',
  growthSubtitle: 'More visibility and more deliberate growth in the current market',
  growthRecommendedPrefix: 'Recommended for',
  growthFeaturedBadge: 'Recommended',
  growthPriorityHigh: 'High priority',
  growthHeroVisibilityTitle: 'Increase visibility',
  growthHeroVisibilityTitleWithContext: 'Increase visibility in {context}',
  growthExpectedEffectLabel: 'Expected effect',
  growthPositionTitle: 'Your position',
  growthVisibilityLabel: 'Visibility',
  growthVisibilityLow: 'Low',
  growthResponseLabel: 'Response time',
  growthResponseMedium: 'Medium',
  growthWhyNowTitle: 'Why now?',
  growthDemandInContext: 'High demand in {context}',
  growthDemandGeneric: 'High demand in the current market',
  growthMarketChanceCurrent: 'Strong market opportunity in the current time range',
  growthVisibilityBelowAverage: 'Your profile sits below the local average',
  growthFocusLabel: 'Focus',
  growthDemandLabel: 'Demand',
  growthDemandHighValue: 'High',
  growthCompetitionLabel: 'Competition',
  growthCompetitionMedium: 'Medium',
  growthConversionLabel: 'Conversion',
  growthConversionOptimizable: 'Can improve',
  growthMarketCompareLabel: 'Market comparison',
  growthMarketCompareAvailable: 'Available',
  growthHighlightCta: 'Increase visibility',
  growthLocalAdsCta: 'View region',
  growthPremiumCta: 'Open insights',
  growthNextStepsTitle: 'Next steps',
  growthNextStepVisibility: 'Improve profile visibility',
  growthNextStepLocalAds: 'Activate promotion',
  growthNextStepLocalAdsWithContext: 'Activate promotion in {context}',
  growthNextStepPricing: 'Review pricing strategy',
  kpiSuccessRateLabel: 'Success rate',
  kpiNoCompletedJobs: 'No completed jobs yet',
  kpiActiveProvidersLabel: 'Active providers',
  kpiActiveRequestsHintSuffix: 'active requests',
  kpiActiveCitiesLabel: 'Active cities',
  kpiWithDemandHint: 'with demand',
  kpiAverageRatingLabel: 'Average rating',
  kpiNoOpenRequests: 'No open requests',
  kpiTotalInRangeHintSuffix: 'total in selected range',
  kpiLast7DaysHintSuffix: 'in the last 7 days',
  kpiNoRecentOffers7d: 'No offers in the last 7 days',
  kpiResponseTimeLabel: 'Response time',
  kpiNoResponseTimeData: 'No response-time data yet',
  kpiFastResponseHint: 'Strong: under 30 min',
  kpiResponseTargetHint: 'Target: under 30 min',
  kpiAcceptedOffersHintSuffix: 'accepted offers',
  kpiNoSentOffers: 'No sent offers yet',
  kpiProfileCompletenessLabel: 'Profile completeness',
  kpiStrongProfileHint: 'Strong profile',
  kpiImproveProfileHint: 'Improve profile for better visibility',
  emptyDemand: 'No category demand data for this range.',
  emptyCities: 'No city demand data yet.',
  emptyInsights: 'No insights available yet.',
  emptyActivity: 'No activity data yet.',
  fallbackGeneralCategoryLabel: 'General',
  peakLabel: 'Peak activity point',
  bestWindowLabel: 'Best time window',
  updatedLabel: 'Last updated',
  requestsLabel: 'Requests',
  offersLabel: 'Offers',
  reviewsLabel: 'Reviews',
  stage1LabelPlatform: 'Requests',
  stage2LabelPlatform: 'Offers',
  stage3LabelPlatform: 'Wins',
  stage4LabelPlatform: 'Completed jobs',
  stage1LabelPersonalized: 'Open requests',
  stage2LabelPersonalized: 'Sent offers',
  stage3LabelPersonalized: 'Accepted offers',
  stage4LabelPersonalized: 'Completed jobs',
  funnelRequestsLabel: 'Requests',
  funnelRequestsCompactLabel: 'Requests',
  funnelOffersLabel: 'Provider offers',
  funnelOffersCompactLabel: 'Offers',
  funnelConfirmedLabel: 'Confirmed responses',
  funnelConfirmedCompactLabel: 'Responses',
  funnelClosedLabel: 'Closed contracts',
  funnelClosedCompactLabel: 'Contracts',
  funnelCompletedLabel: 'Successfully completed',
  funnelCompletedCompactLabel: 'Completed',
  funnelProfitLabel: 'Profit amount',
  funnelProfitCompactLabel: 'Profit',
  funnelRateOfferLabel: 'Response rate',
  funnelRateConfirmationLabel: 'Approval rate',
  funnelRateClosureLabel: 'Closure rate',
  funnelRateCompletionLabel: 'Fulfillment rate',
  funnelRateAvgRevenueLabel: 'Avg revenue / job',
  funnelSummaryPrefix: 'From',
  funnelSummaryMiddle: 'requests,',
  funnelSummarySuffix: 'were successfully completed.',
  funnelDropoffLabel: 'Drop-off highlight',
  funnelEmptyTitle: 'No funnel data available yet',
  funnelEmptyBody:
    'As soon as first requests, offers, and completions are available, your platform performance will appear here.',
  funnelError: 'Funnel data could not be loaded. Please try again later.',
  conversionLabel: 'Conversion',
  growthCta: 'Discover more',
};
