'use client';

import { buildRequestsListProps } from '@/components/requests/requestsListProps';
import {
  buildRequestsPublicContentProps,
  buildRequestsPublicFiltersProps,
} from '@/components/requests/requestsPublicContent.model';
import { PublicContent } from '@/features/workspace/requests';
import { I18N_KEYS } from '@/lib/i18n/keys';
import { resolveRequestsListDensityForPageSize } from '@/lib/requests/pagination';
import type { RequestsExplorerRequestsContentProps } from '@/components/requests/requestsExplorer.types';

export function RequestsExplorerRequestsContent({
  t,
  locale,
  emptyCtaHref,
  topBar,
  categoryOptions,
  serviceOptions,
  cityOptions,
  sortOptions,
  categoryKey,
  subcategoryKey,
  cityId,
  sortBy,
  totalResultsLabel,
  isCategoriesLoading,
  isServicesLoading,
  isPending,
  appliedFilterChips,
  onCategoryChange,
  onSubcategoryChange,
  onCityChange,
  onSortChange,
  onReset,
  requests,
  isLoading,
  isError,
  enableOfferActions = true,
  showFavoriteButton = true,
  offersByRequest,
  favoriteRequestIds,
  pendingFavoriteRequestIds,
  pendingOfferRequestId,
  totalPages,
  openOfferSheet,
  onWithdrawOffer,
  toggleRequestFavorite,
  serviceByKey,
  categoryByKey,
  cityById,
  formatDate,
  formatPrice,
  page,
  limit,
  setPage,
  listDensity,
  onListDensityChange,
  summaryStripProps,
  isSummaryStripLoading,
}: RequestsExplorerRequestsContentProps) {
  const onPrevPage = () => setPage(Math.max(1, page - 1));
  const onNextPage = () => setPage(Math.min(totalPages, page + 1));

  return (
    <PublicContent
      {...buildRequestsPublicContentProps({
        t,
        filtersProps: buildRequestsPublicFiltersProps({
          t,
          locale,
          categoryOptions,
          serviceOptions,
          cityOptions,
          sortOptions,
          categoryKey,
          subcategoryKey,
          cityId,
          sortBy,
          totalResults: totalResultsLabel,
          isCategoriesLoading,
          isServicesLoading,
          isPending,
          appliedChips: appliedFilterChips,
          onCategoryChange,
          onSubcategoryChange,
          onCityChange,
          onSortChange,
          onReset,
        }),
        statusFilters: [],
        activeStatusFilter: 'all',
        onStatusFilterChange: () => {},
        isLoading,
        isError,
        requestsCount: requests.length,
        hasActivePublicFilter: appliedFilterChips.length > 0,
        emptyCtaHref,
        requestsListProps: buildRequestsListProps({
          t,
          locale,
          requests,
          isLoading,
          isError,
          serviceByKey,
          categoryByKey,
          cityById,
          formatDate,
          formatPrice,
          enableOfferActions,
          offersByRequest,
          favoriteRequestIds,
          pendingFavoriteRequestIds,
          onToggleFavorite: (requestId) => {
            void toggleRequestFavorite(requestId);
          },
          onSendOffer: openOfferSheet,
          onEditOffer: openOfferSheet,
          onWithdrawOffer,
          pendingOfferRequestId,
          showFavoriteButton,
        }),
        page,
        totalPages,
        resultsLabel: t(I18N_KEYS.requestsPage.countLabel),
        onPrevPage,
        onNextPage,
        listDensity: listDensity ?? resolveRequestsListDensityForPageSize(limit),
        onListDensityChange,
        header: topBar,
        summaryStripProps,
        isSummaryStripLoading,
      })}
    />
  );
}
