import { z } from 'zod';

const rangeSchema = z.enum(['24h', '7d', '30d', '90d']);
const toneSchema = z.enum(['positive', 'neutral', 'warning']);

const selectedFilterSchema = z.object({
  value: z.string().nullable(),
  label: z.string(),
});

const filterOptionSchema = z.object({
  value: z.string(),
  label: z.string(),
  disabled: z.boolean().optional(),
});

const contextHealthSchema = z.object({
  key: z.enum(['demand', 'competition', 'activity']),
  value: z.enum(['rising', 'stable', 'limited', 'high', 'balanced', 'low']),
  tone: toneSchema,
});

const cityDemandSchema = z.object({
  citySlug: z.string(),
  cityName: z.string(),
  cityId: z.string().nullable(),
  requestCount: z.number(),
  auftragSuchenCount: z.number().nullable().optional(),
  anbieterSuchenCount: z.number().nullable().optional(),
  marketBalanceRatio: z.number().nullable().optional(),
  signal: z.enum(['high', 'medium', 'low', 'none']).optional(),
  lat: z.number().nullable(),
  lng: z.number().nullable(),
});

const categoryDemandSchema = z.object({
  categoryKey: z.string().nullable(),
  categoryName: z.string(),
  requestCount: z.number(),
  sharePercent: z.number(),
});

const opportunitySchema = z.object({
  rank: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  cityId: z.string().nullable(),
  city: z.string(),
  categoryKey: z.string().nullable(),
  category: z.string().nullable(),
  demand: z.number(),
  providers: z.number().nullable(),
  marketBalanceRatio: z.number().nullable(),
  score: z.number(),
  demandScore: z.number(),
  competitionScore: z.number(),
  growthScore: z.number(),
  activityScore: z.number(),
  status: z.enum(['very_high', 'good', 'balanced', 'competitive', 'low']),
  tone: z.enum(['very-high', 'high', 'balanced', 'supply-heavy']),
  summaryKey: z.enum(['very_high', 'good', 'balanced_competitive', 'balanced', 'competitive', 'low_demand', 'low']),
  metrics: z.array(z.object({
    key: z.enum(['demand', 'competition', 'growth', 'activity']),
    value: z.number(),
    semanticTone: z.enum(['very-high', 'high', 'medium', 'low']),
    semanticKey: z.enum(['very_high', 'high', 'noticeable', 'medium', 'low']),
  })),
  peerContext: z.object({
    role: z.enum(['focus', 'competitor']),
    distanceKm: z.number().nullable(),
    reason: z.enum(['selected_city', 'nearby_competitor', 'top_ranked']),
  }).nullable().optional(),
  priceIntelligence: z.object({
    citySlug: z.string().nullable(),
    city: z.string().nullable(),
    categoryKey: z.string().nullable(),
    category: z.string().nullable(),
    recommendedMin: z.number().nullable(),
    recommendedMax: z.number().nullable(),
    marketAverage: z.number().nullable(),
    optimalMin: z.number().nullable(),
    optimalMax: z.number().nullable(),
    smartRecommendedPrice: z.number().nullable(),
    smartSignalTone: z.enum(['visibility', 'balanced', 'premium']).nullable(),
    analyzedRequestsCount: z.number().nullable(),
    confidenceLevel: z.enum(['high', 'medium', 'low']).nullable(),
    recommendation: z.string().nullable(),
    profitPotentialScore: z.number().nullable(),
    profitPotentialStatus: z.enum(['high', 'medium', 'low']).nullable(),
  }).nullable().optional(),
});

export const workspaceStatisticsDecisionDashboardSchema = z.object({
  __source: z.enum(['bff', 'fallback']),
  updatedAt: z.string(),
  mode: z.enum(['platform', 'personalized']),
  range: rangeSchema,
  decisionContext: z.object({
    mode: z.enum(['global', 'focus']),
    period: rangeSchema,
    city: selectedFilterSchema,
    region: selectedFilterSchema.nullable().optional(),
    category: selectedFilterSchema,
    service: selectedFilterSchema.nullable().optional(),
    scopeLabel: z.string().nullable().optional(),
    title: z.string().nullable().optional(),
    subtitle: z.string().nullable().optional(),
    stickyLabel: z.string().nullable().optional(),
    health: z.array(contextHealthSchema),
    lowData: z.object({
      isLowData: z.boolean(),
      title: z.string().nullable().optional(),
      body: z.string().nullable().optional(),
    }).optional(),
  }),
  filterOptions: z.object({
    cities: z.array(filterOptionSchema),
    categories: z.array(filterOptionSchema),
    services: z.array(filterOptionSchema),
  }),
  sectionMeta: z.object({
    decisionSubtitle: z.string().nullable().optional(),
    demandSubtitle: z.string().nullable().optional(),
    citiesSubtitle: z.string().nullable().optional(),
    opportunityTitle: z.string().nullable().optional(),
    priceTitle: z.string().nullable().optional(),
    insightsSubtitle: z.string().nullable().optional(),
    growthSubtitle: z.string().nullable().optional(),
  }),
  exportMeta: z.object({
    filename: z.string().nullable().optional(),
  }),
  summary: z.object({
    totalPublishedRequests: z.number(),
    totalActiveProviders: z.number(),
    totalActiveCities: z.number(),
    platformRatingAvg: z.number(),
    platformRatingCount: z.number(),
  }),
  kpis: z.object({
    requestsTotal: z.number(),
    offersTotal: z.number(),
    completedJobsTotal: z.number(),
    successRate: z.number(),
    avgResponseMinutes: z.number().nullable(),
    profileCompleteness: z.number().nullable(),
    openRequests: z.number().nullable(),
    recentOffers7d: z.number().nullable(),
  }),
  demand: z.object({
    categories: z.array(categoryDemandSchema),
    cities: z.array(cityDemandSchema),
  }),
  opportunityRadar: z.array(opportunitySchema),
  profileFunnel: z.object({
    periodLabel: z.string(),
    stages: z.array(z.object({
      id: z.enum(['requests', 'offers', 'confirmations', 'contracts', 'completed', 'revenue']),
      label: z.string(),
      value: z.number(),
      displayValue: z.string(),
      widthPercent: z.number(),
      rateLabel: z.string().nullable(),
      ratePercent: z.number().nullable(),
      helperText: z.string().nullable(),
    })),
    summaryText: z.string(),
    totalConversionPercent: z.number(),
    conversionRate: z.number(),
    profitAmount: z.number(),
  }).passthrough(),
  insights: z.array(z.object({
    code: z.string(),
    level: z.enum(['info', 'trend', 'warning']),
    context: z.string().nullable(),
  }).passthrough()),
  growthCards: z.array(z.object({
    key: z.string(),
    href: z.string(),
    title: z.string().optional(),
    body: z.string().optional(),
    benefit: z.string().optional(),
    tone: z.enum(['primary', 'default']).optional(),
    badge: z.string().optional(),
    recommendedFor: z.string().optional(),
  })),
  activity: z.object({
    range: rangeSchema,
    interval: z.enum(['hour', 'day']),
    points: z.array(z.object({
      timestamp: z.string(),
      requests: z.number(),
      offers: z.number(),
    })),
    totals: z.object({
      requestsTotal: z.number(),
      offersTotal: z.number(),
      latestRequests: z.number(),
      latestOffers: z.number(),
      previousRequests: z.number(),
      previousOffers: z.number(),
      peakTimestamp: z.string().nullable(),
      bestWindowTimestamp: z.string().nullable(),
    }),
    metrics: z.object({
      offerRatePercent: z.number(),
      responseMedianMinutes: z.number().nullable(),
      unansweredRequests24h: z.number(),
      cancellationRatePercent: z.number(),
      completedJobs: z.number(),
      gmvAmount: z.number(),
      platformRevenueAmount: z.number(),
      takeRatePercent: z.number(),
      offerRateTone: toneSchema,
      responseMedianTone: toneSchema,
      unansweredTone: toneSchema,
      cancellationTone: toneSchema,
      completedTone: toneSchema,
      revenueTone: toneSchema,
    }),
  }),
  priceIntelligence: z.object({
    citySlug: z.string().nullable(),
    city: z.string().nullable(),
    categoryKey: z.string().nullable(),
    category: z.string().nullable(),
    recommendedMin: z.number().nullable(),
    recommendedMax: z.number().nullable(),
    marketAverage: z.number().nullable(),
    optimalMin: z.number().nullable(),
    optimalMax: z.number().nullable(),
    smartRecommendedPrice: z.number().nullable(),
    smartSignalTone: z.enum(['visibility', 'balanced', 'premium']).nullable(),
    analyzedRequestsCount: z.number().nullable(),
    confidenceLevel: z.enum(['high', 'medium', 'low']).nullable(),
    recommendation: z.string().nullable(),
    profitPotentialScore: z.number().nullable(),
    profitPotentialStatus: z.enum(['high', 'medium', 'low']).nullable(),
  }).optional(),
  decisionInsight: z.string().nullable().optional(),
});

export type WorkspaceStatisticsDecisionDashboardSchema = z.infer<typeof workspaceStatisticsDecisionDashboardSchema>;
