'use client';

import * as React from 'react';

import { buildWorkspacePrivateViewModel } from '@/features/workspace/requests/workspaceViewModel.model';
import type { WorkspaceContentProps } from '@/features/workspace/requests/workspaceContent.types';
import type { PrivateInput } from '@/features/workspace/requests/workspaceViewModel.types';

type UseWorkspacePrivateViewModelParams = PrivateInput & {
  enabled?: boolean;
};

export function useWorkspacePrivateViewModel({
  enabled = true,
  ...params
}: UseWorkspacePrivateViewModelParams): {
  workspaceContentProps: WorkspaceContentProps | null;
} {
  const {
    t,
    locale,
    isWorkspaceAuthed,
    activeWorkspaceTab,
    showWorkspaceHeader,
    showWorkspaceHeading,
    primaryAction,
    onPrimaryActionClick,
    statusFilters,
    activeStatusFilter,
    setStatusFilter,
    isMyRequestsLoading,
    filteredMyRequests,
    ownerRequestActions,
    isMyOffersLoading,
    filteredMyOffers,
    myOfferRequests,
    isProviderContractsLoading,
    isClientContractsLoading,
    filteredContracts,
    contractRequests,
    contractOffersByRequest,
    isFavoritesLoading,
    favoritesItems,
    hasFavoriteRequests,
    hasFavoriteProviders,
    resolvedFavoritesView,
    setFavoritesView,
    favoriteRequests,
    isFavoriteRequestsLoading,
    favoriteProviderCards,
    isMyReviewsLoading,
    myReviews,
    isPersonalized,
    offersByRequest,
    favoriteRequestIds,
    onToggleRequestFavorite,
    onOpenOfferSheet,
    onWithdrawOffer,
    onOpenChatThread,
    pendingOfferRequestId,
    pendingFavoriteRequestIds,
    serviceByKey,
    categoryByKey,
    cityById,
    formatDate,
    formatPrice,
  } = params;

  const workspaceContentProps = React.useMemo(
    () => {
      if (!enabled) {
        return null;
      }

      return buildWorkspacePrivateViewModel({
        t,
        locale,
        isWorkspaceAuthed,
        activeWorkspaceTab,
        showWorkspaceHeader,
        showWorkspaceHeading,
        primaryAction,
        onPrimaryActionClick,
        statusFilters,
        activeStatusFilter,
        setStatusFilter,
        isMyRequestsLoading,
        filteredMyRequests,
        ownerRequestActions,
        isMyOffersLoading,
        filteredMyOffers,
        myOfferRequests,
        isProviderContractsLoading,
        isClientContractsLoading,
        filteredContracts,
        contractRequests,
        contractOffersByRequest,
        isFavoritesLoading,
        favoritesItems,
        hasFavoriteRequests,
        hasFavoriteProviders,
        resolvedFavoritesView,
        setFavoritesView,
        favoriteRequests,
        isFavoriteRequestsLoading,
        favoriteProviderCards,
        isMyReviewsLoading,
        myReviews,
        isPersonalized,
        offersByRequest,
        favoriteRequestIds,
        onToggleRequestFavorite,
        onOpenOfferSheet,
        onWithdrawOffer,
        onOpenChatThread,
        pendingOfferRequestId,
        pendingFavoriteRequestIds,
        serviceByKey,
        categoryByKey,
        cityById,
        formatDate,
        formatPrice,
      }).workspaceContentProps;
    },
    [
      activeStatusFilter,
      activeWorkspaceTab,
      categoryByKey,
      cityById,
      contractOffersByRequest,
      contractRequests,
      favoriteProviderCards,
      favoriteRequestIds,
      favoriteRequests,
      favoritesItems,
      filteredContracts,
      filteredMyOffers,
      filteredMyRequests,
      formatDate,
      formatPrice,
      hasFavoriteProviders,
      hasFavoriteRequests,
      isClientContractsLoading,
      isWorkspaceAuthed,
      isFavoriteRequestsLoading,
      isFavoritesLoading,
      isMyOffersLoading,
      isMyRequestsLoading,
      isMyReviewsLoading,
      isPersonalized,
      isProviderContractsLoading,
      enabled,
      locale,
      myOfferRequests,
      myReviews,
      offersByRequest,
      onOpenChatThread,
      onOpenOfferSheet,
      onPrimaryActionClick,
      onToggleRequestFavorite,
      onWithdrawOffer,
      ownerRequestActions,
      pendingFavoriteRequestIds,
      pendingOfferRequestId,
      primaryAction,
      resolvedFavoritesView,
      serviceByKey,
      setFavoritesView,
      setStatusFilter,
      showWorkspaceHeader,
      showWorkspaceHeading,
      statusFilters,
      t,
    ],
  );

  return {
    workspaceContentProps,
  };
}
