'use client';

import * as React from 'react';

import type { WorkspaceStatusFilter } from '@/features/workspace/requests/workspace.types';
import { buildWorkspacePrivateContentProps } from '@/features/workspace/requests/workspaceViewModel.private';
import {
  buildWorkspacePublicContentProps,
  buildWorkspacePublicFiltersProps,
} from '@/features/workspace/requests/workspaceViewModel.public';
import type {
  PrivateInput,
  PublicInput,
} from '@/features/workspace/requests/workspaceViewModel.types';

export function useWorkspacePrivateViewModel(params: PrivateInput) {
  const {
    t,
    locale,
    activeWorkspaceTab,
    showWorkspaceHeader,
    showWorkspaceHeading,
    primaryAction,
    onPrimaryActionClick,
    statusFilters,
    activeStatusFilter,
    setStatusFilter,
    isMyRequestsLoading,
    filteredMyRequests,
    ownerRequestActions,
    isMyOffersLoading,
    filteredMyOffers,
    myOfferRequests,
    isProviderContractsLoading,
    isClientContractsLoading,
    filteredContracts,
    contractRequests,
    contractOffersByRequest,
    isFavoritesLoading,
    favoritesItems,
    hasFavoriteRequests,
    hasFavoriteProviders,
    resolvedFavoritesView,
    setFavoritesView,
    favoriteRequests,
    isFavoriteRequestsLoading,
    favoriteProviderCards,
    isMyReviewsLoading,
    myReviews,
    activeReviewsView,
    setReviewsView,
    reviewCards,
    isPersonalized,
    offersByRequest,
    favoriteRequestIds,
    onToggleRequestFavorite,
    onOpenOfferSheet,
    onWithdrawOffer,
    onOpenChatThread,
    pendingOfferRequestId,
    pendingFavoriteRequestIds,
    serviceByKey,
    categoryByKey,
    cityById,
    formatDate,
    formatPrice,
  } = params;

  const workspaceContentProps = React.useMemo(
    () =>
      buildWorkspacePrivateContentProps({
        t,
        locale,
        activeWorkspaceTab,
        showWorkspaceHeader,
        showWorkspaceHeading,
        primaryAction,
        onPrimaryActionClick,
        statusFilters,
        activeStatusFilter,
        setStatusFilter,
        isMyRequestsLoading,
        filteredMyRequests,
        ownerRequestActions,
        isMyOffersLoading,
        filteredMyOffers,
        myOfferRequests,
        isProviderContractsLoading,
        isClientContractsLoading,
        filteredContracts,
        contractRequests,
        contractOffersByRequest,
        isFavoritesLoading,
        favoritesItems,
        hasFavoriteRequests,
        hasFavoriteProviders,
        resolvedFavoritesView,
        setFavoritesView,
        favoriteRequests,
        isFavoriteRequestsLoading,
        favoriteProviderCards,
        isMyReviewsLoading,
        myReviews,
        activeReviewsView,
        setReviewsView,
        reviewCards,
        isPersonalized,
        offersByRequest,
        favoriteRequestIds,
        onToggleRequestFavorite,
        onOpenOfferSheet,
        onWithdrawOffer,
        onOpenChatThread,
        pendingOfferRequestId,
        pendingFavoriteRequestIds,
        serviceByKey,
        categoryByKey,
        cityById,
        formatDate,
        formatPrice,
      }),
    [
      activeReviewsView,
      activeStatusFilter,
      activeWorkspaceTab,
      categoryByKey,
      cityById,
      contractOffersByRequest,
      contractRequests,
      favoriteProviderCards,
      favoriteRequestIds,
      favoriteRequests,
      favoritesItems,
      filteredContracts,
      filteredMyOffers,
      filteredMyRequests,
      formatDate,
      formatPrice,
      hasFavoriteProviders,
      hasFavoriteRequests,
      isClientContractsLoading,
      isFavoriteRequestsLoading,
      isFavoritesLoading,
      isMyOffersLoading,
      isMyRequestsLoading,
      isMyReviewsLoading,
      isPersonalized,
      isProviderContractsLoading,
      locale,
      myOfferRequests,
      myReviews,
      offersByRequest,
      onOpenChatThread,
      onOpenOfferSheet,
      onPrimaryActionClick,
      onToggleRequestFavorite,
      onWithdrawOffer,
      ownerRequestActions,
      pendingFavoriteRequestIds,
      pendingOfferRequestId,
      primaryAction,
      resolvedFavoritesView,
      reviewCards,
      serviceByKey,
      setFavoritesView,
      setReviewsView,
      setStatusFilter,
      showWorkspaceHeader,
      showWorkspaceHeading,
      statusFilters,
      t,
    ],
  );

  return {
    workspaceContentProps,
  };
}

export function useWorkspacePublicViewModel(params: PublicInput) {
  const {
    t,
    locale,
    categoryOptions,
    serviceOptions,
    cityOptions,
    sortOptions,
    categoryKey,
    subcategoryKey,
    cityId,
    sortBy,
    totalResultsLabel,
    isCategoriesLoading,
    isServicesLoading,
    isFiltersPending,
    appliedFilterChips,
    onCategoryChangeTracked,
    onSubcategoryChangeTracked,
    onCityChangeTracked,
    onSortChangeTracked,
    onResetTracked,
    statusFilters,
    activeStatusFilter,
    setStatusFilter,
    isLoading,
    isError,
    requestsCount,
    hasActivePublicFilter,
    requests,
    serviceByKey,
    categoryByKey,
    cityById,
    formatDate,
    formatPrice,
    isPersonalized,
    offersByRequest,
    favoriteRequestIds,
    onToggleRequestFavorite,
    onOpenOfferSheet,
    onWithdrawOffer,
    onOpenChatThread,
    pendingOfferRequestId,
    pendingFavoriteRequestIds,
    page,
    totalPages,
    setPage,
  } = params;

  const onStatusFilterChange = React.useCallback(
    (status: string) => setStatusFilter(status as WorkspaceStatusFilter),
    [setStatusFilter],
  );
  const onPrevPage = React.useCallback(() => setPage(Math.max(1, page - 1)), [page, setPage]);
  const onNextPage = React.useCallback(
    () => setPage(Math.min(totalPages, page + 1)),
    [page, setPage, totalPages],
  );

  const filtersProps = React.useMemo(
    () =>
      buildWorkspacePublicFiltersProps({
        t,
        locale,
        categoryOptions,
        serviceOptions,
        cityOptions,
        sortOptions,
        categoryKey,
        subcategoryKey,
        cityId,
        sortBy,
        totalResultsLabel,
        isCategoriesLoading,
        isServicesLoading,
        isFiltersPending,
        appliedFilterChips,
        onCategoryChangeTracked,
        onSubcategoryChangeTracked,
        onCityChangeTracked,
        onSortChangeTracked,
        onResetTracked,
      }),
    [
      appliedFilterChips,
      categoryKey,
      categoryOptions,
      cityId,
      cityOptions,
      isCategoriesLoading,
      isFiltersPending,
      isServicesLoading,
      locale,
      onCategoryChangeTracked,
      onCityChangeTracked,
      onResetTracked,
      onSortChangeTracked,
      onSubcategoryChangeTracked,
      serviceOptions,
      sortBy,
      sortOptions,
      subcategoryKey,
      t,
      totalResultsLabel,
    ],
  );

  const publicContentProps = React.useMemo(
    () =>
      buildWorkspacePublicContentProps({
        t,
        locale,
        statusFilters,
        activeStatusFilter,
        isLoading,
        isError,
        requestsCount,
        hasActivePublicFilter,
        requests,
        serviceByKey,
        categoryByKey,
        cityById,
        formatDate,
        formatPrice,
        isPersonalized,
        offersByRequest,
        favoriteRequestIds,
        onToggleRequestFavorite,
        onOpenOfferSheet,
        onWithdrawOffer,
        onOpenChatThread,
        pendingOfferRequestId,
        pendingFavoriteRequestIds,
        page,
        totalPages,
        filtersProps,
        onStatusFilterChange,
        onPrevPage,
        onNextPage,
      }),
    [
      activeStatusFilter,
      categoryByKey,
      cityById,
      filtersProps,
      formatDate,
      formatPrice,
      hasActivePublicFilter,
      isError,
      isLoading,
      isPersonalized,
      locale,
      onNextPage,
      onOpenChatThread,
      onOpenOfferSheet,
      onPrevPage,
      onStatusFilterChange,
      onToggleRequestFavorite,
      onWithdrawOffer,
      offersByRequest,
      page,
      pendingFavoriteRequestIds,
      pendingOfferRequestId,
      requests,
      requestsCount,
      serviceByKey,
      statusFilters,
      t,
      totalPages,
      favoriteRequestIds,
    ],
  );

  return {
    publicContentProps,
  };
}
