'use client';

import type { ComponentProps } from 'react';

import type { WorkspaceContent } from '@/features/workspace/requests/WorkspaceContent';
import type { PrivateInput } from '@/features/workspace/requests/workspaceViewModel.types';

export function buildWorkspacePrivateContentProps(
  params: PrivateInput,
): ComponentProps<typeof WorkspaceContent> {
  const {
    t,
    locale,
    isWorkspaceAuthed,
    activeWorkspaceTab,
    showWorkspaceHeader,
    showWorkspaceHeading,
    primaryAction,
    onPrimaryActionClick,
    statusFilters,
    activeStatusFilter,
    setStatusFilter,
    isMyRequestsLoading,
    filteredMyRequests,
    ownerRequestActions,
    isMyOffersLoading,
    filteredMyOffers,
    myOfferRequests,
    isProviderContractsLoading,
    isClientContractsLoading,
    filteredContracts,
    contractRequests,
    contractOffersByRequest,
    isFavoritesLoading,
    favoritesItems,
    hasFavoriteRequests,
    hasFavoriteProviders,
    resolvedFavoritesView,
    setFavoritesView,
    favoriteRequests,
    isFavoriteRequestsLoading,
    favoriteProviderCards,
    isMyReviewsLoading,
    myReviews,
    isPersonalized,
    offersByRequest,
    favoriteRequestIds,
    onToggleRequestFavorite,
    onOpenOfferSheet,
    onWithdrawOffer,
    onOpenChatThread,
    pendingOfferRequestId,
    pendingFavoriteRequestIds,
    serviceByKey,
    categoryByKey,
    cityById,
    formatDate,
    formatPrice,
  } = params;

  return {
    t,
    isWorkspaceAuthed,
    activeWorkspaceTab,
    showWorkspaceHeader,
    showWorkspaceHeading,
    primaryAction,
    onPrimaryActionClick,
    statusFilters,
    activeStatusFilter,
    setStatusFilter,
    myRequestsState: {
      isLoading: isMyRequestsLoading,
      isEmpty: filteredMyRequests.length === 0,
    },
    myRequestsListProps: {
      t,
      locale,
      requests: filteredMyRequests,
      isLoading: isMyRequestsLoading,
      isError: false,
      serviceByKey,
      categoryByKey,
      cityById,
      formatDate,
      formatPrice,
      ownerRequestActions,
    },
    myOffersState: {
      isLoading: isMyOffersLoading,
      isEmpty: filteredMyOffers.length === 0,
    },
    myOffersListProps: {
      t,
      locale,
      requests: myOfferRequests,
      isLoading: isMyOffersLoading,
      isError: false,
      serviceByKey,
      categoryByKey,
      cityById,
      formatDate,
      formatPrice,
      enableOfferActions: true,
      hideRecurringBadge: true,
      showFavoriteButton: false,
      offersByRequest,
      onSendOffer: onOpenOfferSheet,
      onEditOffer: onOpenOfferSheet,
      onWithdrawOffer,
      onOpenChatThread,
      pendingOfferRequestId,
    },
    contractsState: {
      isLoading: isProviderContractsLoading || isClientContractsLoading,
      isEmpty: filteredContracts.length === 0,
    },
    contractsListProps: {
      t,
      locale,
      requests: contractRequests,
      isLoading: isProviderContractsLoading || isClientContractsLoading,
      isError: false,
      serviceByKey,
      categoryByKey,
      cityById,
      formatDate,
      formatPrice,
      enableOfferActions: true,
      hideRecurringBadge: true,
      showFavoriteButton: false,
      offersByRequest: contractOffersByRequest,
      onOpenChatThread,
    },
    favoritesState: {
      isLoading: isFavoritesLoading,
      isEmpty: favoritesItems.length === 0,
      hasFavoriteRequests,
      hasFavoriteProviders,
      resolvedView: resolvedFavoritesView,
    },
    onFavoritesViewChange: setFavoritesView,
    favoriteRequestsListProps: {
      t,
      locale,
      requests: favoriteRequests,
      isLoading: isFavoriteRequestsLoading,
      isError: false,
      serviceByKey,
      categoryByKey,
      cityById,
      formatDate,
      formatPrice,
      enableOfferActions: true,
      hideRecurringBadge: isPersonalized,
      showFavoriteButton: true,
      offersByRequest,
      favoriteRequestIds,
      onToggleFavorite: onToggleRequestFavorite,
      onSendOffer: onOpenOfferSheet,
      onEditOffer: onOpenOfferSheet,
      onWithdrawOffer,
      onOpenChatThread,
      pendingOfferRequestId,
      pendingFavoriteRequestIds,
    },
    favoriteProvidersNode: favoriteProviderCards,
    reviewsState: {
      isLoading: isMyReviewsLoading,
      items: myReviews,
    },
  };
}
